### ISSUE TITLE
Python: support for multiline package_dir entries

### ISSUE THREAD

**Issue by gmacon** [pkgw/cranko#21]
I tried this on a Python package using a `src/` layout, as described in [setuptools' docs](https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#using-a-src-layout). I got this error:

```
error: could not initialize app and project graph
caused by: could not parse file `.../foo/setup.cfg` as "ini"-style configuration
caused by: line 19:0: Key cannot be empty
```

Changing

```
package_dir=
    =src
```

to

```
package_dir= =src
```

fixed the problem, though.

That makes me suspect the INI parser isn't handling the "dangling list" format, or, at least, isn't expecting it for this key.

**Comment by pkgw** [comment]
Thanks for trying Cranko and reporting your issue!

I suspect that you're right that the parser doesn't support the format you mention. Cranko uses the [`configparser`](https://crates.io/crates/configparser) crate for `setup.cfg` parsing. We use version 1.0, and I see that the latest release is 2.1.0, so it's possible that this will be fixed with a simple upgrade of the dependency.

Out of curiosity, do you have a particular reason for using the multi-line syntax for this field? I certainly aspire for Cranko to accept a wide range of input files, but in this particular case, "just don't use that syntax" seems like it could potentially be a reasonable response ....

**Comment by gmacon** [comment]
I had used the multiline syntax here because that's what's in setuptools' documentation, but I don't think I've ever actually used the ability for this field to have multiple values.

`configparser`'s README says "Keep in mind that key-value pairs or section headers cannot span multiple lines." so it looks like that's an intentional choice. Now I'm wondering why it didn't break on all the *other* multi-line values in my setup.cfg...

I guess I'm happy with "Don't do that, then" as the answer here.

Thanks for thinking about it, though.
